steps:
  # Build backend (server) image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/qlhs-server:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/qlhs-server:latest'
      - '-f'
      - 'server/Dockerfile'
      - './server'
    id: 'build-server'

  # Build frontend (web) image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/qlhs-web:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/qlhs-web:latest'
      - '-f'
      - 'web/Dockerfile'
      - '--build-arg'
      - 'VITE_API_URL=$_VITE_API_URL'
      - '--build-arg'
      - 'VITE_GOOGLE_CLIENT_ID=$_GOOGLE_CLIENT_ID'
      - './web'
    id: 'build-web'

  # Push backend image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/qlhs-server:$COMMIT_SHA'
    id: 'push-server'
    waitFor: ['build-server']

  # Push frontend image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/qlhs-web:$COMMIT_SHA'
    id: 'push-web'
    waitFor: ['build-web']

  # Deploy backend to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'qlhs-server'
      - '--image'
      - 'gcr.io/$PROJECT_ID/qlhs-server:$COMMIT_SHA'
      - '--region'
      - 'asia-southeast1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '3500'
      - '--set-env-vars'
      - 'NODE_ENV=production'
      - '--set-env-vars'
      - 'DB_SOCKET_PATH=/cloudsql/$_INSTANCE_CONNECTION_NAME'
      - '--set-env-vars'
      - 'DB_USER=$_DB_USER'
      - '--set-env-vars'
      - 'DB_PASS=$_DB_PASS'
      - '--set-env-vars'
      - 'DB_NAME=$_DB_NAME'
      - '--set-env-vars'
      - 'JWT_SECRET=$_JWT_SECRET'
      - '--set-env-vars'
      - 'GOOGLE_CLIENT_ID=$_GOOGLE_CLIENT_ID'
      - '--add-cloudsql-instances'
      - '$_INSTANCE_CONNECTION_NAME'
    id: 'deploy-server'
    waitFor: ['push-server']

  # Deploy frontend to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'qlhs-web'
      - '--image'
      - 'gcr.io/$PROJECT_ID/qlhs-web:$COMMIT_SHA'
      - '--region'
      - 'asia-southeast1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '80'
    id: 'deploy-web'
    waitFor: ['push-web', 'deploy-server']

images:
  - 'gcr.io/$PROJECT_ID/qlhs-server:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/qlhs-server:latest'
  - 'gcr.io/$PROJECT_ID/qlhs-web:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/qlhs-web:latest'

options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY

timeout: '1800s'

substitutions:
  _VITE_API_URL: 'https://qlhs-server-311534268252.asia-southeast1.run.app/api'
  _INSTANCE_CONNECTION_NAME: 'qlhsdtnt:asia-southeast1:qlhs-db-instance' # Default or override in Trigger
  _DB_USER: 'qlhs_user' # Default or override in Trigger
  _DB_PASS: 'needs_to_be_set_in_trigger' # SECURITY: Set this in Cloud Build Trigger
  _DB_NAME: 'qlhs_db'
  _JWT_SECRET: 'needs_to_be_set_in_trigger' # SECURITY: Set this in Cloud Build Trigger
  _GOOGLE_CLIENT_ID: '311534268252-fjpb2dvc8kpne0hrca4fr9pb5k9sspeh.apps.googleusercontent.com'
